# syntax=docker/dockerfile:1
FROM python:3.12-slim
WORKDIR /code
#COPY ./requirements.txt /code/requirements.txt
#RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
#COPY ./task /code/task
#CMD ["celery", "-A", "task.tasks", "worker"]
COPY ./ /code/src
RUN pip install --no-cache-dir --upgrade -r /code/src/worker/requirements.txt
CMD ["celery", "-A", "src.worker.task.tasks", "worker", "-l", "info"]